DROP DATABASE IF EXISTS BANCO;
CREATE DATABASE BANCO;
USE BANCO;

CREATE TABLE ESTADO(
	ID INT NOT NULL  AUTO_INCREMENT
	,NOME VARCHAR(255) NOT NULL UNIQUE 
	,SIGLA CHAR(2) NOT NULL UNIQUE 
	,CONSTRAINT PK_ESTADO PRIMARY KEY (ID)
);

INSERT INTO ESTADO (NOME, SIGLA) VALUES ('ACRE','AC');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('ALAGOAS','AL');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('CEARÁ','CE');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('PIAUÍ','PI');
